### ISSUE TITLE
unicode fun

### ISSUE THREAD

**Issue by aleksandra-tarkowska** [openmicroscopy/snoopycrimecop#188]
when coping and pasting commit massage to https://github.com/aleksandra-tarkowska/openmicroscopy/commit/3091e4c it turned out that `...` appeared as non ASCII character. When `scc merge develop` I had an error:

```
2014-09-09 11:20:36,796 [   scc.merge] INFO  Excluding Pull Request(s) labelled as exclude or breaking
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/scc/main.py", line 72, in entry_point
    (UpdateSubmodules.NAME, UpdateSubmodules),
  File "/Library/Python/2.7/site-packages/scc/framework.py", line 186, in main
    ns.func(ns)
  File "/Library/Python/2.7/site-packages/scc/git.py", line 2511, in __call__
    updated = self.merge(args, self.main_repo)
  File "/Library/Python/2.7/site-packages/scc/git.py", line 2544, in merge
    set_commit_status=args.set_commit_status)
  File "/Library/Python/2.7/site-packages/scc/git.py", line 1326, in rmerge
    set_commit_status=set_commit_status)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1089: ordinal not in range(128)
```

Might be worth to get some support for unicode

**Comment by mtbc** [comment]
Also ran into this with https://github.com/openmicroscopy/ome-documentation/pull/1319. :smiley:

**Comment by sbesson** [comment]
Note this unicode issue is fundamentally related to the fact that Jenkins use non-interactive shell where no `LANG` is set by default

```
[sbesson@ome-ci-c6-02 ome-documentation]$ ~/.local/bin/scc merge regions 
2016-03-01 10:01:03,559 [   scc.merge] INFO  Merging Pull Request(s) based on regions
2016-03-01 10:01:03,560 [   scc.merge] INFO  Including Pull Request(s) opened by any public member of the organization
2016-03-01 10:01:03,560 [   scc.merge] INFO  Including Pull Request(s) labelled as include
2016-03-01 10:01:03,561 [   scc.merge] INFO  Excluding Pull Request(s) labelled as exclude or breaking
2016-03-01 10:01:09,299 [   scc.merge] INFO  Repository: openmicroscopy/ome-documentation
2016-03-01 10:01:09,300 [   scc.merge] INFO  Already up-to-date.
2016-03-01 10:01:09,300 [   scc.merge] INFO  
2016-03-01 10:01:09,300 [   scc.merge] INFO  Merged PRs:
2016-03-01 10:01:09,300 [   scc.merge] INFO    # PR 1408 mtbc 'note 5.2 → 5.3m1 changes to model object glossary'
2016-03-01 10:01:09,300 [   scc.merge] INFO  
[sbesson@ome-ci-c6-02 ome-documentation]$ git checkout origin/regions
Previous HEAD position was 6dac7a4... merge regions -Dorg -Snone
HEAD is now at b220a30... Merge pull request #1413 from ximenesuk/import-template
[sbesson@ome-ci-c6-02 ome-documentation]$ unset LANG
[sbesson@ome-ci-c6-02 ome-documentation]$ ~/.local/bin/scc merge regions 
2016-03-01 10:01:29,779 [   scc.merge] INFO  Merging Pull Request(s) based on regions
2016-03-01 10:01:29,779 [   scc.merge] INFO  Including Pull Request(s) opened by any public member of the organization
2016-03-01 10:01:29,779 [   scc.merge] INFO  Including Pull Request(s) labelled as include
2016-03-01 10:01:29,780 [   scc.merge] INFO  Excluding Pull Request(s) labelled as exclude or breaking
2016-03-01 10:01:33,835 [     scc.git] INFO  Conflict detection failed
2016-03-01 10:01:33,855 [     scc.git] INFO    # PR 1408 mtbc 'note 5.2 → 5.3m1 changes to model object glossary'
Conflicting PR.
Possible conflicts:
  - Conflict detection failed
    - None
2016-03-01 10:01:33,903 [   scc.merge] INFO  Repository: openmicroscopy/ome-documentation
2016-03-01 10:01:33,904 [   scc.merge] INFO  Already up-to-date.
2016-03-01 10:01:33,904 [   scc.merge] INFO  
2016-03-01 10:01:33,904 [   scc.merge] INFO  Conflicting PRs (not included):
2016-03-01 10:01:33,904 [   scc.merge] INFO    # PR 1408 mtbc 'note 5.2 → 5.3m1 changes to model object glossary'
2016-03-01 10:01:33,904 [   scc.merge] INFO  
[sbesson@ome-ci-c6-02 ome-documentation]$ 
```

**Comment by aleksandra-tarkowska** [comment]
The same happened when travis was in progress on https://github.com/IDR/idr-metadata/pull/202 see https://idr-ci.openmicroscopy.org:8443/job/IDR-metadata-push/4/console. Travis green and job is blue

**Comment by sbesson** [comment]
With #216 included, this issue should be solved and I expect we handle unicode in most places. Future bugs can be reported as follow-up issues.
